#! /bin/bash
#compile the device tree overlay and copy to the firmware folder
#dtc -O dtb -o BBB-AHRS-00A0.dtbo -b 0 -@ BBB-AHRS-00A0.dts
#cp -r BBB-AHRS-00A0.dtbo /lib/firmware
#rm -rf BBB-AHRS*

#enable the can interface on startup
cp can_setup.sh /usr/bin/
chmod +x /usr/bin/can_setup.sh
cp can_setup.service /lib/systemd/system/
#create symbolic link
ln -s /lib/systemd/system/can_setup.service /etc/systemd/system/can_setup.service
#Make systemd aware of your new service
systemctl daemon-reload
systemctl enable can_setup.service
systemctl start can_setup.service
